<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProveedorSeeder extends Seeder
{
    public function run()
    {
        DB::table('proveedor')->insert([
            [
                'ID_Proveedor' => 1,
                'Nombre' => 'Tagpad',
                'Direccion' => '4 Troy Terrace',
                'Ciudad' => 'Al Ya‘rubīyah',
                'CodigoPostal' => 'SY',
                'Pais' => 'Syria',
                'Telefono' => '306-609-9284',
                'Fax' => '172-174-9918',
                'Email' => 'nlaxton0@newyorker.com',
            ],
            [
                'ID_Proveedor' => 2,
                'Nombre' => 'Wikivu',
                'Direccion' => '322 Fieldstone Parkway',
                'Ciudad' => 'Valparaíso',
                'CodigoPostal' => 'BR',
                'Pais' => 'Brazil',
                'Telefono' => '626-914-0129',
                'Fax' => '807-393-2536',
                'Email' => 'rbrookwood1@com.com',
            ],
            [
                'ID_Proveedor' => 3,
                'Nombre' => 'Midel',
                'Direccion' => '35804 Esker Center',
                'Ciudad' => 'Omuo-Ekiti',
                'CodigoPostal' => 'NG',
                'Pais' => 'Nigeria',
                'Telefono' => '624-809-4697',
                'Fax' => '461-729-9571',
                'Email' => 'fallix2@omniture.com',
            ],
            [
                'ID_Proveedor' => 4,
                'Nombre' => 'Topicshots',
                'Direccion' => '0 Waywood Park',
                'Ciudad' => 'Jiangkou',
                'CodigoPostal' => 'CN',
                'Pais' => 'China',
                'Telefono' => '548-555-5870',
                'Fax' => '863-742-2231',
                'Email' => 'wcalderon3@elegantthemes.com',
            ],
            [
                'ID_Proveedor' => 5,
                'Nombre' => 'Skidoo',
                'Direccion' => '97 Green Ridge Plaza',
                'Ciudad' => 'Mavingouni',
                'CodigoPostal' => 'KM',
                'Pais' => 'Comoros',
                'Telefono' => '674-130-8470',
                'Fax' => '247-411-9207',
                'Email' => 'kpabel4@themeforest.net',
            ],
            [
                'ID_Proveedor' => 6,
                'Nombre' => 'Fivebridge',
                'Direccion' => '308 Burrows Lane',
                'Ciudad' => 'Shanghu',
                'CodigoPostal' => 'CN',
                'Pais' => 'China',
                'Telefono' => '465-973-9870',
                'Fax' => '225-623-6538',
                'Email' => 'mmorden5@bluehost.com',
            ],
            [
                'ID_Proveedor' => 7,
                'Nombre' => 'Skipstorm',
                'Direccion' => '20 Thierer Park',
                'Ciudad' => 'Palampal',
                'CodigoPostal' => 'ID',
                'Pais' => 'Indonesia',
                'Telefono' => '674-238-9424',
                'Fax' => '267-256-1840',
                'Email' => 'mick6@msu.edu',
            ],
            [
                'ID_Proveedor' => 8,
                'Nombre' => 'Feedbug',
                'Direccion' => '26 Kingsford Place',
                'Ciudad' => 'Bošnjaci',
                'CodigoPostal' => 'HR',
                'Pais' => 'Croatia',
                'Telefono' => '410-320-5445',
                'Fax' => '694-253-9459',
                'Email' => 'atainton7@tamu.edu',
            ],
            [
                'ID_Proveedor' => 9,
                'Nombre' => 'Browsedrive',
                'Direccion' => '5 Mcguire Center',
                'Ciudad' => 'Curiapo',
                'CodigoPostal' => 'VE',
                'Pais' => 'Venezuela',
                'Telefono' => '558-138-5974',
                'Fax' => '264-766-8011',
                'Email' => 'kcooling8@cnbc.com',
            ],
            [
                'ID_Proveedor' => 10,
                'Nombre' => 'Quire',
                'Direccion' => '34 Dapin Terrace',
                'Ciudad' => 'Moju',
                'CodigoPostal' => 'BR',
                'Pais' => 'Brazil',
                'Telefono' => '805-559-5624',
                'Fax' => '995-474-2211',
                'Email' => 'fgiscken9@vinaora.com',
            ],
            [
                'ID_Proveedor' => 11,
                'Nombre' => 'Skiptube',
                'Direccion' => '90583 Melvin Crossing',
                'Ciudad' => 'Rathnew',
                'CodigoPostal' => 'IE',
                'Pais' => 'Ireland',
                'Telefono' => '954-337-3130',
                'Fax' => '107-794-9229',
                'Email' => 'ecoltherda@clickbank.net',
            ],
            [
                'ID_Proveedor' => 12,
                'Nombre' => 'Eazzy',
                'Direccion' => '88443 Westend Lane',
                'Ciudad' => 'Balingasag',
                'CodigoPostal' => 'PH',
                'Pais' => 'Philippines',
                'Telefono' => '402-591-6078',
                'Fax' => '371-871-9425',
                'Email' => 'bbriamob@washingtonpost.com',
            ],
            [
                'ID_Proveedor' => 13,
                'Nombre' => 'Meejo',
                'Direccion' => '9 Scott Circle',
                'Ciudad' => 'Vale da Serra',
                'CodigoPostal' => 'PT',
                'Pais' => 'Portugal',
                'Telefono' => '410-991-1278',
                'Fax' => '766-380-0359',
                'Email' => 'tcorbertc@howstuffworks.com',
            ],
            [
                'ID_Proveedor' => 14,
                'Nombre' => 'Yadel',
                'Direccion' => '43007 Merrick Drive',
                'Ciudad' => 'Podkamennaya Tunguska',
                'CodigoPostal' => 'RU',
                'Pais' => 'Russia',
                'Telefono' => '844-916-9504',
                'Fax' => '530-704-4462',
                'Email' => 'awarburtond@spiegel.de',
            ],
            [
                'ID_Proveedor' => 15,
                'Nombre' => 'Dabfeed',
                'Direccion' => '73 Bay Point',
                'Ciudad' => 'Bagumbayan',
                'CodigoPostal' => 'PH',
                'Pais' => 'Philippines',
                'Telefono' => '678-280-6816',
                'Fax' => '888-252-3688',
                'Email' => 'bphilippse@wired.com',
            ],
            [
                'ID_Proveedor' => 16,
                'Nombre' => 'Omba',
                'Direccion' => '24 Iowa Hill',
                'Ciudad' => 'Ladhewāla Warāich',
                'CodigoPostal' => 'PK',
                'Pais' => 'Pakistan',
                'Telefono' => '474-397-2751',
                'Fax' => '257-395-3451',
                'Email' => 'rduchasteauf@arizona.edu',
            ],
            [
                'ID_Proveedor' => 17,
                'Nombre' => 'Wikibox',
                'Direccion' => '49492 Rieder Avenue',
                'Ciudad' => 'Middelburg',
                'CodigoPostal' => 'ZA',
                'Pais' => 'South Africa',
                'Telefono' => '924-286-5103',
                'Fax'                => '227-554-6973',
                'Email' => 'wdenziloeg@plala.or.jp',
            ],
            [
                'ID_Proveedor' => 18,
                'Nombre' => 'Quaxo',
                'Direccion' => '87 Macpherson Parkway',
                'Ciudad' => 'Binuangeun',
                'CodigoPostal' => 'ID',
                'Pais' => 'Indonesia',
                'Telefono' => '488-377-1480',
                'Fax' => '955-634-7257',
                'Email' => 'tsimmh@issuu.com',
            ],
            [
                'ID_Proveedor' => 19,
                'Nombre' => 'Gabtype',
                'Direccion' => '4 Summit Street',
                'Ciudad' => 'Bin’an',
                'CodigoPostal' => 'CN',
                'Pais' => 'China',
                'Telefono' => '904-894-8423',
                'Fax' => '548-858-9563',
                'Email' => 'jiddyi@multiply.com',
            ],
            [
                'ID_Proveedor' => 20,
                'Nombre' => 'Janyx',
                'Direccion' => '3 Thackeray Plaza',
                'Ciudad' => 'Petropavlivka',
                'CodigoPostal' => 'UA',
                'Pais' => 'Ukraine',
                'Telefono' => '793-163-0463',
                'Fax' => '766-465-7112',
                'Email' => 'hhurleyj@zdnet.com',
            ],
        ]);
    }
}